// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SendMetricClient is the client API for SendMetric service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendMetricClient interface {
	Send(ctx context.Context, in *Metrics, opts ...grpc.CallOption) (*OkStatus, error)
}

type sendMetricClient struct {
	cc grpc.ClientConnInterface
}

func NewSendMetricClient(cc grpc.ClientConnInterface) SendMetricClient {
	return &sendMetricClient{cc}
}

func (c *sendMetricClient) Send(ctx context.Context, in *Metrics, opts ...grpc.CallOption) (*OkStatus, error) {
	out := new(OkStatus)
	err := c.cc.Invoke(ctx, "/proto.SendMetric/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendMetricServer is the server API for SendMetric service.
// All implementations must embed UnimplementedSendMetricServer
// for forward compatibility
type SendMetricServer interface {
	Send(context.Context, *Metrics) (*OkStatus, error)
	mustEmbedUnimplementedSendMetricServer()
}

// UnimplementedSendMetricServer must be embedded to have forward compatible implementations.
type UnimplementedSendMetricServer struct {
}

func (UnimplementedSendMetricServer) Send(context.Context, *Metrics) (*OkStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedSendMetricServer) mustEmbedUnimplementedSendMetricServer() {}

// UnsafeSendMetricServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendMetricServer will
// result in compilation errors.
type UnsafeSendMetricServer interface {
	mustEmbedUnimplementedSendMetricServer()
}

func RegisterSendMetricServer(s grpc.ServiceRegistrar, srv SendMetricServer) {
	s.RegisterService(&SendMetric_ServiceDesc, srv)
}

func _SendMetric_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Metrics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMetricServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SendMetric/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMetricServer).Send(ctx, req.(*Metrics))
	}
	return interceptor(ctx, in, info, handler)
}

// SendMetric_ServiceDesc is the grpc.ServiceDesc for SendMetric service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendMetric_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SendMetric",
	HandlerType: (*SendMetricServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _SendMetric_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
